### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by JVickery-TBS** [ToferC/data_docs#1]
**Local setup (on Ubuntu 20.04):**
cargo v1.61.0
rustc v1.61.0
diesel_cli v1.4.1
psql v13.7

**Local build errors:**

```
error: generic parameters may not be used in const operations
   --> /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/jetscii-0.4.4/src/simd.rs:109:13
    |
109 |             T::CONTROL_BYTE,
    |             ^^^^^^^^^^^^^^^ cannot perform const operation using `T`
    |
    = note: type parameters may not be used in const expressions

error: generic parameters may not be used in const operations
   --> /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/jetscii-0.4.4/src/simd.rs:148:13
    |
148 |             T::CONTROL_BYTE,
    |             ^^^^^^^^^^^^^^^ cannot perform const operation using `T`
    |
    = note: type parameters may not be used in const expressions

error: could not compile `jetscii` due to 2 previous errors
```

**Inquiry:**
What are the local dependencies required to build the project?

**Comment by ToferC** [comment]
I was testing a crate for ingesting .docx files that was out of date. Since updated to a newer crate that seems to be working. Please note that I am still actively developing this, so there will be some issues. Apologies.

**Comment by JVickery-TBS** [comment]
@ToferC No problem! We were just trying to take a quick look at your tool here and see possible usages for it over here at the Open Government at TBS.
